### PR TITLE
ItemCheck function (items passed as a table)

### PR DESCRIPTION
**Pull request by Brady-F**
This commit changes the check ItemCount function to ItemCheck. ItemCheck works a lot like JobCheck where it checks if the parameter is passed as a table or as a string. If it is of type table it will check all the items and their required quantities. 

The function has been tested only on QB. It will need to be tested on ESX and with OX inventory. Let me know if you have any questions or changes need to be made. 

Here's and example of use in a resource:

```
exports['qtarget']:AddTargetModel({-120287622}, {
        options = {
            {
                type = "client",
                event = "qb-methcar:cook",
                icon = "fas fa-blender",
                label = "Lets cook!",
                item = {
	            ['acetone'] = 5,
	            ['lithium'] = 2,
	            ['methlab'] = 1
                }
            },
        },
        distance = 2.0
    })
```

### CODE REVIEW

**Comment by BerkieBb** [comment]
```lua
ItemCheck = function(item)
	if type(item) == 'table' then
		for k, v in pairs(ESX.GetPlayerData().inventory) do
			if item[v.name] then
				if item[v.name] < v.count then
					return false
				end
			end
		end
		return true
	else
		for _, v in pairs(ESX.GetPlayerData().inventory) do
			if v.name == item then
				return v.count > 0
			end
		end
		return false
	end
end
```
I think this code is better for the ESX ItemCheck

**Comment by BerkieBb** [comment]
```lua
ItemCheck = function(item)
	if type(item) == 'table' then
		for k, v in pairs(PlayerData.items) do
			if item[v.name] then
				if item[v.name] < v.amount then
					return false
				end
			end
		end
		return true
	else
		for _, v in pairs(PlayerData.items) do
			if v.name == item then
				return v.amount > 0
			end
		end
		return false
	end
end
```
This would be it for QB

**Comment by BerkieBb** [comment]
```lua
ItemCheck = function(item)
	if type(item) == 'table' then
		local inventory = exports.ox_inventory:Search(2, item)
		if inventory then
			for name, count in pairs(inventory) do
				if item[name] then
					if item[name] < count then
						return false
					end
				end
			end
			return true
		end
		return false
	else
		return exports.ox_inventory:Search(2, item) > 0
	end
end
```
This would be it for ox inventory

**Comment by Brady-F** [comment]
> ```lua
> ItemCheck = function(item)
> 	if type(item) == 'table' then
> 		for k, v in pairs(PlayerData.items) do
> 			if item[v.name] then
> 				if item[v.name] < v.amount then
> 					return false
> 				end
> 			end
> 		end
> 		return true
> 	else
> 		for _, v in pairs(PlayerData.items) do
> 			if v.name == item then
> 				return v.amount > 0
> 			end
> 		end
> 		return false
> 	end
> end
> ```
> 
> This would be it for QB

I don't think any of these would work. I tested QB and it does not work. You're only checking if the item count is less than what is needed. You're not checking if the player even has the item. That is why I have the variable which adds up the item count. Additionally this is helpful when the the player has the item across multiple slots.

**Comment by BerkieBb** [comment]
It does check if the player has the item because otherwise it wouldn't be in the table for QB

**Comment by BerkieBb** [comment]
But I think it does miss a check wait

**Comment by Brady-F** [comment]
> But I think it does miss a check wait

Regardless though, I think it wouldn't work if the item is not all in the same inventory slot.

**Comment by BerkieBb** [comment]
Because qb-inventory puts every item in a different table regardless of the similarities

**Comment by BerkieBb** [comment]
This is added with https://github.com/overextended/qtarget/commit/1577da65bbb766a5e4586c3c9610a9095f8ab5a5

**Pull request closed without merging**
